name: python3.12_litestar2.14

on: [push, pull_request]

jobs:
  run-python:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install "litestar==2.14" uvicorn

      - run: litestar run

